project:
  type: website
  output-dir: docs

website:
  title: "jo@tom"
  site-url: "https://joatom.github.io/blog/"
  description: "AI curios"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - text: "Blog" 
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Snippets"
        file: snippets.qmd
    right:
      - about/index.qmd
      - icon: github
        href: https://github.com/joatom
      - icon: twitter
        href: https://twitter.com/JohannesTomason
      - icon: linkedin
        href: https://de.linkedin.com/in/jtomasoni
      - icon: rss
        href: index.xml
  sidebar:
    - id: projects
      title: "Projects"
      style: "docked"
      background: light
      collapse-level: 2
      align: left
      contents: 
        - text: "Projects"
          href: projects.qmd
        - section: "Art"
          contents:
          - projects/art/playing-with-rob/index.qmd
        - section: "Calliope Mini"
          contents:
          - projects/calliope_mini/calliobingo/index.qmd
          - projects/calliope_mini/calliopris/index.qmd
          - projects/calliope_mini/callipianotech/index.qmd
          - projects/calliope_mini/callirun/index.qmd
        - section: "Fitbit"
          contents:
          - projects/fitbit/watchtrain/index.qmd

  #cookie-consent:
  #  type: express
  #  style: interstitial
  #  palette: dark

  page-footer: 
    left:
      - text: "Copyright 2022, Johannes Tomasoni" 
    center:
      - text: "Imprint"
        href: legal/imprint.qmd
      - text: "Privacy Policy"
        href: legal/privacy.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto


