project:
  type: website
  output-dir: docs

website:
  title: "AI curious"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joatom
      - icon: twitter
        href: https://twitter.com/JohannesTomason
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto


